CREATE DATABASE IF NOT EXISTS Perco
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE Perco;

CREATE TABLE IF NOT EXISTS user(
  id VARCHAR(128) PRIMARY KEY, 
  jsonstr VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS director(
  id VARCHAR(128) PRIMARY KEY, 
  jsonstr VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS gym(
	id VARCHAR(128),
	gymid VARCHAR(128),
	INDEX idx1(id)
);

CREATE TABLE IF NOT EXISTS feed(
   no INT UNSIGNED PRIMARY KEY,
   id VARCHAR(128),
   jsonstr VARCHAR(1024)
);


